## UNITS

# Get all units.

GET http://localhost:9080/simple-rpg/api/units

###

# Get single unit.

GET http://localhost:9080/simple-rpg/api/units/a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c56f

###

# Get single unit. Not existing, created later.

GET http://localhost:9080/simple-rpg/api/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83

###

# Get single unit portrait.

GET http://localhost:9080/simple-rpg/api/units/a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c56f/portrait

###

# Get single unit portrait. Not existing, created later.

GET http://localhost:9080/simple-rpg/api/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83/portrait

###

# Create new unit.

PUT http://localhost:9080/simple-rpg/api/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83
Content-Type: application/json

{
  "name": "Medic2",
  "description": "Medic is the life saver.",
  "id": "a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c56f",
  "leadership": 1,
  "movement": 1,
  "save": 3,
  "toughness": 2,
  "wounds": 2
}

###
GET http://localhost:9080/simple-rpg/api/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83


###
# Create unit portrait.

PUT http://localhost:9080/simple-rpg/api/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83/portrait
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="sigrid.png'

< warhammer-list-creator/src/main/resources/pl/edu/pg/eti/kask/list/configuration/avatar/sigrid.png
--boundary--

###

# Update unit.

PATCH http://localhost:9080/simple-rpg/api/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83
Content-Type: application/json

{
  "name": "Medic2",
  "movement": 13,
  "save": 4
}

###

# Delete unit.

DELETE http://localhost:9080/simple-rpg/api/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83

###










##ARMIES

###

# Get all armies.

GET http://localhost:9080/simple-rpg/api/armies

###

# Get single army.

GET http://localhost:9080/simple-rpg/api/armies/f1e2d3c4-b5a6-7980-1a2b-3c4d5e6f7a8b
###


# Get all user armies.

GET http://localhost:9080/simple-rpg/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/armies

###

# Create new army.

PUT http://localhost:9080/simple-rpg/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/armies/c4804e0f-769e-4ab9-9ebe-0578fb4f0dd6
Content-Type: application/json

{
  "name": "Space Wolves",
  "description": "Bloodclaw Legion"
}

###

# USERS

###

# Get all user characters.

GET http://localhost:9080/simple-rpg/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/characters

###

# Get all user characters. Empty.

GET http://localhost:9080/simple-rpg/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/characters

###

# Get all user characters. Not existing.

GET http://localhost:9080/simple-rpg/api/users/c07cab55-a56f-4d67-b351-175bb7a94b7a/characters
