## UNITS

# Get all units.

GET http://localhost:9080/list-creator/api/v1/units

###

# Get single unit.

GET http://localhost:9080/list-creator/api/v1/units/a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c56f

###

# Get single unit. Not existing, created later.

GET http://localhost:9080/list-creator/api/v1/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83

###

# Get single unit portrait.

GET http://localhost:9080/list-creator/api/v1/units/a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c56f/portrait

###

# Get single unit portrait. Not existing, created later.

GET http://localhost:9080/list-creator/api/v1/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83/portrait

###

# Create new unit.

PUT http://localhost:9080/list-creator/api/v1/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83
Content-Type: application/json

{
  "name": "Medic2",
  "description": "Medic is the life saver.",
  "id": "a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c56f",
  "leadership": 1,
  "movement": 1,
  "save": 3,
  "toughness": 2,
  "wounds": 2
}

###
GET http://localhost:9080/list-creator/api/v1/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83


###
# Create unit portrait.

PUT http://localhost:9080/list-creator/api/v1/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83/portrait
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="apothecary.jpg'

< warhammer-list-creator/src/main/resources/pl/edu/pg/eti/kask/list/configuration/avatar/apothecary.jpg
--boundary--

###

# Update unit.

PATCH http://localhost:9080/list-creator/api/v1/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83
Content-Type: application/json

{
  "name": "Medic3",
  "description": "Medic is the life saver.",
  "leadership": 3,
  "movement": 2,
  "save": 4,
  "toughness": 2,
  "wounds": 2
}

###

# Delete unit.

DELETE http://localhost:9080/list-creator/api/v1/units/3c6f1eb1-8069-44ab-988f-d7fed2b65d83

###










##ARMIES

###

# Get all armies.

GET http://localhost:9080/list-creator/api/v1/armies

###

# Get single army.

GET http://localhost:9080/list-creator/api/v1/armies/f1e2d3c4-b5a6-7980-1a2b-3c4d5e6f7a8b
###


# Get all user armies.

GET http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/armies

###

# Create new army.

PUT http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/armies/c4804e0f-769e-4ab9-9ebe-0578fb4f0dd6
Content-Type: application/json

{
  "name": "Space Wolves",
  "description": "Bloodclaw Legion"
}
###

#Get created army.

GET http://localhost:9080/list-creator/api/v1/armies/c4804e0f-769e-4ab9-9ebe-0578fb4f0dd6
###

GET http://localhost:9080/list-creator/api/v1/armies/f1e2d3c4-b5a6-7980-1a2b-3c4d5e6f7a8b

###

## SQUADS

## Put 15 scouts to squad.

PUT http://localhost:9080/list-creator/api/v1/squads/f1e2d3c4-b5a6-7980-1a2b-3c4d5e6f7a54
Content-Type: application/json

{
  "armyId": "c4804e0f-769e-4ab9-9ebe-0578fb4f0dd6",
  "unitId": "d3f3b1e4-2f4a-4f0a-8e2e-6f5e8f1c9b7a",
  "count": 15
}
###

# Put 6 Intercessors to squad.
###

PUT http://localhost:9080/list-creator/api/v1/squads/f1e2d3c4-b5a6-7980-1a2b-3c4d5e6f7a21
Content-Type: application/json

{
  "armyId": "f1e2d3c4-b5a6-7980-1a2b-3c4d5e6f7a8b",
  "unitId": "525d3e7b-bb1f-4c13-bf17-926d1a12e4c0",
  "count": 6
}
###

# Delete squad.
###TODO
DELETE http://localhost:9080/list-creator/api/v1/squads/f1e2d3c4-b5a6-7980-1a2b-3c4d5e6f7a21

###
#Delete army.

DELETE http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/armies/c4804e0f-769e-4ab9-9ebe-0578fb4f0dd6





# USERS

###

# Get users.

GET http://localhost:9080/list-creator/api/v1/users

###

# Get single user.

GET http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###
#Get non existing user

GET http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a2
###

# Create new user

PUT http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a2
Content-Type: application/json

{
  "login": "lukasz",
  "password": "lukasz",
  "email": "lukasz@example.com",
  "name": "lukasz",
  "surname": "Walczak",
  "birthDate": "1990-01-01"
}
###

# Delete user

DELETE http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a2

###

# Create user portrait.

PUT http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="apothecary.jpg'

< warhammer-list-creator/src/main/resources/pl/edu/pg/eti/kask/list/configuration/avatar/apothecary.jpg
--boundary--

###

# Get user portrait.

GET http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait

###

# Delete user portrait.

DELETE http://localhost:9080/list-creator/api/v1/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/portrait

###